/**
 * CloudSentinel Theme Presets
 * Each preset defines CSS custom property values that override the defaults in index.css.
 * Category determines whether html.light class is added (for components with hardcoded light checks).
 */

const THEMES = [
  {
    id: 'dark',
    name: 'Dark',
    category: 'dark',
    description: 'Default dark theme with violet accents',
    preview: { bg: '#0f1419', primary: '#7c3aed', accent: '#38bdf8' },
    colors: {
      '--color-primary': '#7c3aed',
      '--color-primary-light': '#a78bfa',
      '--color-primary-dark': '#6d28d9',
      '--color-surface': '#0f1419',
      '--color-surface-light': '#1a2332',
      '--color-surface-lighter': '#2a3a4e',
      '--color-accent': '#38bdf8',
      '--color-accent-light': '#7dd3fc',
      '--color-success': '#4ade80',
      '--color-warning': '#facc15',
      '--color-danger': '#fb7185',
      '--color-danger-light': '#fda4af',
      '--color-info': '#60a5fa',
      '--color-text': '#f8fafc',
      '--color-text-muted': '#a1b4cf',
      '--color-border': '#293548',
    },
  },
  {
    id: 'light',
    name: 'Light',
    category: 'light',
    description: 'Clean light theme for bright environments',
    preview: { bg: '#f5f5f0', primary: '#4f46e5', accent: '#0891b2' },
    colors: {
      '--color-primary': '#4f46e5',
      '--color-primary-light': '#6366f1',
      '--color-primary-dark': '#4338ca',
      '--color-surface': '#f5f5f0',
      '--color-surface-light': '#ffffff',
      '--color-surface-lighter': '#e8e8e3',
      '--color-accent': '#0891b2',
      '--color-accent-light': '#06b6d4',
      '--color-success': '#16a34a',
      '--color-warning': '#ca8a04',
      '--color-danger': '#dc2626',
      '--color-danger-light': '#ef4444',
      '--color-info': '#2563eb',
      '--color-text': '#1a1a1a',
      '--color-text-muted': '#6b7280',
      '--color-border': '#d1d5db',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'dark',
    description: 'Deep navy corporate theme',
    preview: { bg: '#0c1222', primary: '#3b82f6', accent: '#06b6d4' },
    colors: {
      '--color-primary': '#3b82f6',
      '--color-primary-light': '#60a5fa',
      '--color-primary-dark': '#2563eb',
      '--color-surface': '#0c1222',
      '--color-surface-light': '#162033',
      '--color-surface-lighter': '#1e3050',
      '--color-accent': '#06b6d4',
      '--color-accent-light': '#22d3ee',
      '--color-success': '#10b981',
      '--color-warning': '#f59e0b',
      '--color-danger': '#ef4444',
      '--color-danger-light': '#f87171',
      '--color-info': '#3b82f6',
      '--color-text': '#f1f5f9',
      '--color-text-muted': '#94a3b8',
      '--color-border': '#1e3a5f',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    category: 'dark',
    description: 'Teal and green aquatic theme',
    preview: { bg: '#0a1a1f', primary: '#14b8a6', accent: '#22d3ee' },
    colors: {
      '--color-primary': '#14b8a6',
      '--color-primary-light': '#2dd4bf',
      '--color-primary-dark': '#0d9488',
      '--color-surface': '#0a1a1f',
      '--color-surface-light': '#132a30',
      '--color-surface-lighter': '#1c3a42',
      '--color-accent': '#22d3ee',
      '--color-accent-light': '#67e8f9',
      '--color-success': '#34d399',
      '--color-warning': '#fbbf24',
      '--color-danger': '#f87171',
      '--color-danger-light': '#fca5a5',
      '--color-info': '#38bdf8',
      '--color-text': '#ecfdf5',
      '--color-text-muted': '#86c5b8',
      '--color-border': '#1a4a52',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    category: 'dark',
    description: 'Warm orange and amber tones',
    preview: { bg: '#1a1008', primary: '#f59e0b', accent: '#fb923c' },
    colors: {
      '--color-primary': '#f59e0b',
      '--color-primary-light': '#fbbf24',
      '--color-primary-dark': '#d97706',
      '--color-surface': '#1a1008',
      '--color-surface-light': '#2a1e10',
      '--color-surface-lighter': '#3d2e1a',
      '--color-accent': '#fb923c',
      '--color-accent-light': '#fdba74',
      '--color-success': '#4ade80',
      '--color-warning': '#fbbf24',
      '--color-danger': '#ef4444',
      '--color-danger-light': '#f87171',
      '--color-info': '#38bdf8',
      '--color-text': '#fef3c7',
      '--color-text-muted': '#c4a06a',
      '--color-border': '#4a3520',
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    category: 'light',
    description: 'Professional light theme with slate accents',
    preview: { bg: '#f8fafc', primary: '#475569', accent: '#0ea5e9' },
    colors: {
      '--color-primary': '#475569',
      '--color-primary-light': '#64748b',
      '--color-primary-dark': '#334155',
      '--color-surface': '#f8fafc',
      '--color-surface-light': '#ffffff',
      '--color-surface-lighter': '#e2e8f0',
      '--color-accent': '#0ea5e9',
      '--color-accent-light': '#38bdf8',
      '--color-success': '#22c55e',
      '--color-warning': '#eab308',
      '--color-danger': '#ef4444',
      '--color-danger-light': '#f87171',
      '--color-info': '#3b82f6',
      '--color-text': '#0f172a',
      '--color-text-muted': '#64748b',
      '--color-border': '#cbd5e1',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'dark',
    description: 'Clean monochrome with subtle accents',
    preview: { bg: '#111111', primary: '#a3a3a3', accent: '#e5e5e5' },
    colors: {
      '--color-primary': '#a3a3a3',
      '--color-primary-light': '#d4d4d4',
      '--color-primary-dark': '#737373',
      '--color-surface': '#111111',
      '--color-surface-light': '#1a1a1a',
      '--color-surface-lighter': '#262626',
      '--color-accent': '#e5e5e5',
      '--color-accent-light': '#f5f5f5',
      '--color-success': '#4ade80',
      '--color-warning': '#fbbf24',
      '--color-danger': '#f87171',
      '--color-danger-light': '#fca5a5',
      '--color-info': '#93c5fd',
      '--color-text': '#fafafa',
      '--color-text-muted': '#737373',
      '--color-border': '#333333',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    category: 'dark',
    description: 'Maximum readability with strong contrasts',
    preview: { bg: '#000000', primary: '#ffcc00', accent: '#00ffcc' },
    colors: {
      '--color-primary': '#ffcc00',
      '--color-primary-light': '#ffe066',
      '--color-primary-dark': '#e6b800',
      '--color-surface': '#000000',
      '--color-surface-light': '#0a0a0a',
      '--color-surface-lighter': '#1a1a1a',
      '--color-accent': '#00ffcc',
      '--color-accent-light': '#66ffd9',
      '--color-success': '#00ff00',
      '--color-warning': '#ffff00',
      '--color-danger': '#ff0000',
      '--color-danger-light': '#ff4444',
      '--color-info': '#00aaff',
      '--color-text': '#ffffff',
      '--color-text-muted': '#cccccc',
      '--color-border': '#444444',
    },
  },
];

export default THEMES;

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}

export function getThemesByCategory(category) {
  return THEMES.filter((t) => t.category === category);
}
